extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1888
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:9090'
    namespace: test-space
    const_labels:
      label1: value1
      'another label': spaced value
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
    format: proto
  
service:
  extensions: [ health_check, pprof, memory_ballast, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger, zipkin ]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]