# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  
# Alertmanager configuration
# alerting:
  # alertmanagers:
    # - static_configs:
        # - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: cadvisor
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['cadvisor:9102']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: jaeger
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: opentelemetry-collector
    static_configs:
      - targets: ['opentelemetry-collector:9464']

  - job_name: zipkin-server
    static_configs:
      - targets: ['zipkin-server:9411']
      
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:3001']

  - job_name: vector
    static_configs:
      - targets: ['vector:9160']